quarto::quarto_render('Reference.qmd', output_file = 'app/Reference.md')
quarto::quarto_render('Licence_in_app.qmd', output_file = 'app/license.md')
quarto::quarto_render('Contact.qmd', output_file = 'app/Contact.md')
quarto::quarto_render('Instructions.qmd', output_file = 'app/Instructions.md')
quarto::quarto_render('Changelog.qmd', output_file = 'app/Changelog.md')
